# Generated by Django 5.0.6 on 2024-06-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecozone", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeseriesRedispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("direction", models.CharField(max_length=40)),
                ("power_mid_mw", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "redispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecozone.redispatch",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["start", "direction"],
                        name="ecozone_ti_start_7bbac6_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="timeseriesredispatch",
            constraint=models.UniqueConstraint(
                fields=("start", "redispatch"),
                name="unique_timeseries_redispatch_record",
            ),
        ),
    ]
