# Generated by Django 5.0.6 on 2024-06-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecozone", "0003_alter_gridregion_name_alter_powerplant_name_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gridregion",
            new_name="ecozone_gri_name_ee4cf0_idx",
            old_name="ecozone_gr_name_f1196a_idx",
        ),
        migrations.RenameIndex(
            model_name="powerplant",
            new_name="ecozone_pow_name_597aba_idx",
            old_name="ecozone_po_name_91a105_idx",
        ),
        migrations.RenameIndex(
            model_name="redispatch",
            new_name="ecozone_red_start_5f0695_idx",
            old_name="ecozone_re_start_c20c31_idx",
        ),
        migrations.RenameIndex(
            model_name="timeseriesredispatch",
            new_name="ecozone_tim_start_910ff6_idx",
            old_name="ecozone_ti_start_7bbac6_idx",
        ),
        migrations.RenameIndex(
            model_name="tso",
            new_name="ecozone_tso_name_45bb2b_idx",
            old_name="ecozone_ts_name_ced377_idx",
        ),
    ]
