# Generated by Django 5.0.6 on 2024-06-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecozone", "0005_psrgeneration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="psrgeneration",
            name="emissions",
            field=models.FloatField(null=True),
        ),
    ]
