# Generated by Django 5.0.6 on 2024-08-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecozone', '0009_add_zone_info_to_timeseries'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='psrgeneration',
            index=models.Index(fields=['start'], name='ecozone_psr_start_9c1dfd_idx'),
        ),
    ]
