# Generated by Django 5.0.6 on 2024-11-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecozone", "0012_aggregategenerationforecast_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RenewableGenerationForecastManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RenewableGenerationForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                (
                    "control_area",
                    models.CharField(
                        choices=[
                            ("10YDE-VE-------2", "50Hertz"),
                            ("10YDE-RWENET---I", "Amprion"),
                            ("10YDE-EON------1", "TenneT"),
                            ("10YDE-ENBW-----N", "TransnetBW"),
                        ],
                        max_length=16,
                        verbose_name="Control area",
                    ),
                ),
                (
                    "psr",
                    models.CharField(
                        choices=[
                            ("b01", "Biomasse"),
                            ("b02", "Braunkohle"),
                            ("b03", "Fossil Coal-derived gas"),
                            ("b04", "Erdgas"),
                            ("b05", "Steinkohle"),
                            ("b06", "Mineralöl"),
                            ("b07", "Fossil Oil shale"),
                            ("b08", "Fossil Peat"),
                            ("b09", "Geothermie"),
                            ("b10", "Pumpspeicher"),
                            ("b11", "Wasserkraft (Laufwasser)"),
                            ("b12", "Wasserspeicher"),
                            ("b13", "Marine"),
                            ("b14", "Kernenergie"),
                            ("b15", "Sonstige Erneuerbare Energien"),
                            ("b16", "Photovoltaik"),
                            ("b17", "Abfall"),
                            ("b18", "Windenergie (Offshore-Anlage)"),
                            ("b19", "Windenergie (Onshore-Anlage)"),
                            ("b20", "Sonstige konventionelle Energien"),
                        ],
                        max_length=3,
                        verbose_name="PSR type",
                    ),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("day-ahead", "Dayahead"),
                            ("intraday", "Intraday"),
                            ("current", "Current"),
                        ],
                        max_length=9,
                        verbose_name="Forecast type",
                    ),
                ),
                ("power_mw", models.FloatField(null=True)),
                ("emissions", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["start", "control_area", "psr"],
                        name="ecozone_ren_start_90a45a_idx",
                    ),
                    models.Index(
                        fields=["start", "psr"], name="ecozone_ren_start_23ef02_idx"
                    ),
                    models.Index(fields=["start"], name="ecozone_ren_start_9bc3b5_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="renewablegenerationforecast",
            constraint=models.UniqueConstraint(
                fields=("start", "control_area", "psr"),
                name="unique_renewable_generation_forecast_record",
            ),
        ),
    ]
