# Generated by Django 5.0.6 on 2024-11-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecozone", "0013_renewablegenerationforecastmanager_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Generation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("b01_gen", models.FloatField(null=True)),
                ("b02_gen", models.FloatField(null=True)),
                ("b04_gen", models.FloatField(null=True)),
                ("b05_gen", models.FloatField(null=True)),
                ("b06_gen", models.FloatField(null=True)),
                ("b09_gen", models.FloatField(null=True)),
                ("b10_gen", models.FloatField(null=True)),
                ("b11_gen", models.FloatField(null=True)),
                ("b12_gen", models.FloatField(null=True)),
                ("b14_gen", models.FloatField(null=True)),
                ("b15_gen", models.FloatField(null=True)),
                ("b16_gen", models.FloatField(null=True)),
                ("b17_gen", models.FloatField(null=True)),
                ("b18_gen", models.FloatField(null=True)),
                ("b19_gen", models.FloatField(null=True)),
                ("b20_gen", models.FloatField(null=True)),
                ("b01_em", models.FloatField(null=True)),
                ("b02_em", models.FloatField(null=True)),
                ("b04_em", models.FloatField(null=True)),
                ("b05_em", models.FloatField(null=True)),
                ("b06_em", models.FloatField(null=True)),
                ("b09_em", models.FloatField(null=True)),
                ("b10_em", models.FloatField(null=True)),
                ("b11_em", models.FloatField(null=True)),
                ("b12_em", models.FloatField(null=True)),
                ("b14_em", models.FloatField(null=True)),
                ("b15_em", models.FloatField(null=True)),
                ("b16_em", models.FloatField(null=True)),
                ("b17_em", models.FloatField(null=True)),
                ("b18_em", models.FloatField(null=True)),
                ("b19_em", models.FloatField(null=True)),
                ("b20_em", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="RenewableGenerationForecastManager",
        ),
        migrations.AlterField(
            model_name="aggregategenerationforecast",
            name="control_area",
            field=models.CharField(
                choices=[
                    ("10YDE-VE-------2", "50Hertz"),
                    ("10YDE-RWENET---I", "Amprion"),
                    ("10YDE-EON------1", "TenneT"),
                    ("10YDE-ENBW-----N", "TransnetBW"),
                    ("10Y1001A1001A83F", "Germany"),
                ],
                max_length=16,
                verbose_name="Control area",
            ),
        ),
        migrations.AlterField(
            model_name="psrgeneration",
            name="control_area",
            field=models.CharField(
                choices=[
                    ("10YDE-VE-------2", "50Hertz"),
                    ("10YDE-RWENET---I", "Amprion"),
                    ("10YDE-EON------1", "TenneT"),
                    ("10YDE-ENBW-----N", "TransnetBW"),
                    ("10Y1001A1001A83F", "Germany"),
                ],
                max_length=16,
                verbose_name="Control area",
            ),
        ),
        migrations.AlterField(
            model_name="renewablegenerationforecast",
            name="control_area",
            field=models.CharField(
                choices=[
                    ("10YDE-VE-------2", "50Hertz"),
                    ("10YDE-RWENET---I", "Amprion"),
                    ("10YDE-EON------1", "TenneT"),
                    ("10YDE-ENBW-----N", "TransnetBW"),
                    ("10Y1001A1001A83F", "Germany"),
                ],
                max_length=16,
                verbose_name="Control area",
            ),
        ),
        migrations.AddIndex(
            model_name="generation",
            index=models.Index(fields=["start"], name="ecozone_gen_start_9423d8_idx"),
        ),
        migrations.AddConstraint(
            model_name="generation",
            constraint=models.UniqueConstraint(
                fields=("start",), name="unique_generation_record"
            ),
        ),
    ]
