# Generated by Django 5.0.6 on 2024-11-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecozone", "0015_forecast_forecast_unique_forecast_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="agg_gen",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="forecast",
            name="forecast_type",
            field=models.CharField(
                choices=[
                    ("day-ahead", "Dayahead"),
                    ("intraday", "Intraday"),
                    ("current", "Current"),
                ],
                default="day-ahead",
                max_length=9,
                verbose_name="Forecast type",
            ),
        ),
    ]
