# Generated by Django 5.0.6 on 2024-11-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecozone", "0016_forecast_agg_gen_alter_forecast_forecast_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="generation",
            name="ws_redisual",
            field=models.FloatField(null=True),
        ),
    ]
