# Generated by Django 5.0.6 on 2024-11-26 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecozone", "0017_generation_ws_redisual"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generation",
            old_name="ws_redisual",
            new_name="ws_residual",
        ),
    ]
