# Generated by Django 5.0.6 on 2024-11-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecozone", "0018_rename_ws_redisual_generation_ws_residual"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="ws_residual",
            field=models.FloatField(null=True),
        ),
    ]
