# Generated by Django 5.0.6 on 2024-12-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecozone', '0022_delete_aggregategenerationforecast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriesredispatch',
            name='emissions',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='timeseriesredispatch',
            name='work_mwh',
            field=models.FloatField(),
        ),
    ]
