# Generated by Django 5.0.6 on 2024-12-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecozone', '0023_alter_timeseriesredispatch_emissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriesredispatch',
            name='emissions',
            field=models.FloatField(null=True),
        ),
    ]
