# Generated by Django 5.0.6 on 2025-01-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecozone", "0024_alter_timeseriesredispatch_emissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="powerplant",
            name="is_heat_cogen",
            field=models.BooleanField(null=True),
        ),
    ]
