# Generated by Django 5.0.6 on 2024-05-28 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PowerPlant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Redispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("reason", models.CharField(max_length=30)),
                ("direction", models.CharField(max_length=40)),
                ("power_mid_mw", models.FloatField()),
                ("power_max_mw", models.FloatField()),
                ("work_total_mwh", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TSO",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GridRegion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="eco_zone_gr_name_f1196a_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="gridregion",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_grid_region_record"
            ),
        ),
        migrations.AddIndex(
            model_name="powerplant",
            index=models.Index(fields=["name"], name="eco_zone_po_name_91a105_idx"),
        ),
        migrations.AddConstraint(
            model_name="powerplant",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_power_plant_record"
            ),
        ),
        migrations.AddField(
            model_name="redispatch",
            name="grid_regions",
            field=models.ManyToManyField(to="eco_zone.gridregion"),
        ),
        migrations.AddField(
            model_name="redispatch",
            name="power_plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eco_zone.powerplant"
            ),
        ),
        migrations.AddIndex(
            model_name="tso",
            index=models.Index(fields=["name"], name="eco_zone_ts_name_ced377_idx"),
        ),
        migrations.AddConstraint(
            model_name="tso",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_tso_record"
            ),
        ),
        migrations.AddField(
            model_name="redispatch",
            name="tso_requesting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redispatch_tso_requesting",
                to="eco_zone.tso",
            ),
        ),
        migrations.AddField(
            model_name="redispatch",
            name="tso_supplying",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redispatch_tso_supplying",
                to="eco_zone.tso",
            ),
        ),
        migrations.AddIndex(
            model_name="redispatch",
            index=models.Index(
                fields=["start", "end", "power_plant"],
                name="eco_zone_re_start_c20c31_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="redispatch",
            constraint=models.UniqueConstraint(
                fields=(
                    "start",
                    "end",
                    "reason",
                    "direction",
                    "power_mid_mw",
                    "power_max_mw",
                    "work_total_mwh",
                    "tso_supplying",
                    "tso_requesting",
                    "power_plant",
                ),
                name="unique_redispatch_record",
            ),
        ),
    ]
