# Generated by Django 5.0.6 on 2024-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_zone", "0002_timeseriesredispatch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gridregion",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="powerplant",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="redispatch",
            name="direction",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="redispatch",
            name="reason",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="timeseriesredispatch",
            name="direction",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tso",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
