name: Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.12.3-slim-bullseye

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt update
          apt install -y --no-install-recommends make
          make pip

      - name: Lint code
        run: make lint

      - name: Run tests
        run: make test
